@extends('layouts.app')
@section('title', __('app.transactions'))
@php
$pageTitle = __('app.accounting_transactions');
$breadcrumbs = [['label' => __('app.dashboard'), 'url' => route('dashboard')], ['label' => __('app.accounting'), 'url' => '#'], ['label' => __('app.transactions'), 'url' => '']];
@endphp
@section('content')
<div class="card">
    <div class="card-header flex justify-between items-center"><h3 class="text-lg font-semibold text-gray-800">{{ __('app.accounting_transactions') }}</h3><a href="{{ route('accounting.transactions.create') }}" class="btn btn-primary btn-sm"><svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path></svg>{{ __('app.new_transaction') }}</a></div>
    <div class="mb-4 grid grid-cols-1 md:grid-cols-4 gap-4"><div><input type="date" class="form-control" placeholder="{{ __('app.from_date') }}"></div><div><input type="date" class="form-control" placeholder="{{ __('app.to_date') }}"></div><div><select class="form-control"><option>{{ __('app.all_accounts') }}</option>@foreach($accounts ?? [] as $acc)<option value="{{ $acc->id }}">{{ $acc->name }}</option>@endforeach</select></div><div><select class="form-control"><option>{{ __('app.all_types') }}</option><option value="debit">{{ __('app.debit') }}</option><option value="credit">{{ __('app.credit') }}</option></select></div></div>
    <div class="overflow-x-auto"><table class="table"><thead><tr><th>{{ __('app.date') }}</th><th>{{ __('app.reference') }}</th><th>{{ __('app.account') }}</th><th>{{ __('app.description') }}</th><th>{{ __('app.debit') }}</th><th>{{ __('app.credit') }}</th><th>{{ __('app.running_balance') }}</th><th>{{ __('app.actions') }}</th></tr></thead>
    <tbody>@forelse($transactions ?? [] as $transaction)<tr><td>{{ $transaction->date->format('M d, Y') }}</td><td class="font-semibold">{{ $transaction->reference }}</td><td>{{ $transaction->account->code }} - {{ $transaction->account->name }}</td><td>{{ $transaction->description }}</td><td class="font-semibold {{ $transaction->type == 'debit' ? 'text-red-600' : '' }}">{{ $transaction->type == 'debit' ? number_format($transaction->amount, 2) . ' DH' : '-' }}</td><td class="font-semibold {{ $transaction->type == 'credit' ? 'text-green-600' : '' }}">{{ $transaction->type == 'credit' ? number_format($transaction->amount, 2) . ' DH' : '-' }}</td><td class="font-semibold">{{ number_format($transaction->running_balance ?? 0, 2) }} DH</td><td><a href="{{ route('accounting.transactions.show', $transaction->id) }}" class="text-blue-600" title="{{ __('app.view') }}"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path></svg></a></td></tr>@empty<tr><td colspan="8" class="text-center text-gray-500 py-8">{{ __('app.no_transactions_found') }}</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
