@extends('layouts.app')
@section('title', __('app.stock_adjustments'))
@php
$pageTitle = __('app.stock_adjustments');
$breadcrumbs = [['label' => __('app.dashboard'), 'url' => route('dashboard')], ['label' => __('app.stock'), 'url' => '#'], ['label' => __('app.adjustments'), 'url' => '']];
@endphp
@section('content')
<div class="card">
    <div class="card-header flex justify-between items-center"><h3 class="text-lg font-semibold text-gray-800">{{ __('app.stock_adjustments') }}</h3><a href="{{ route('stock.adjustments.create') }}" class="btn btn-primary btn-sm"><svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path></svg>{{ __('app.new') }} {{ __('app.adjustment') }}</a></div>
    <div class="mb-4 grid grid-cols-1 md:grid-cols-3 gap-4"><div><select class="form-control"><option>{{ __('app.all_warehouses') }}</option>@foreach($warehouses ?? [] as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></div><div><select class="form-control"><option>{{ __('app.all') }} {{ __('app.type') }}</option><option value="addition">{{ __('app.addition') }}</option><option value="subtraction">{{ __('app.subtraction') }}</option><option value="damage">{{ __('app.damage') }}</option><option value="loss">{{ __('app.loss') }}</option></select></div><div><input type="date" class="form-control"></div></div>
    <div class="overflow-x-auto"><table class="table"><thead><tr><th>#</th><th>{{ __('app.reference') }}</th><th>{{ __('app.warehouse') }}</th><th>{{ __('app.date') }}</th><th>{{ __('app.type') }}</th><th>{{ __('app.items') }}</th><th>{{ __('app.reason') }}</th><th>{{ __('app.actions') }}</th></tr></thead>
    <tbody>@forelse($adjustments ?? [] as $adj)<tr><td>{{ $loop->iteration }}</td><td class="font-semibold">{{ $adj->reference }}</td><td>{{ $adj->warehouse->name ?? '-' }}</td><td>{{ $adj->date?->format('M d, Y') ?? $adj->created_at->format('M d, Y') }}</td><td>@if($adj->type == 'addition')<span class="badge badge-success">{{ __('app.addition') }}</span>@elseif($adj->type == 'subtraction')<span class="badge badge-warning">{{ __('app.subtraction') }}</span>@elseif($adj->type == 'damage')<span class="badge badge-danger">{{ __('app.damage') }}</span>@else<span class="badge badge-secondary">{{ __('app.loss') }}</span>@endif</td><td>{{ $adj->notes ? substr_count($adj->notes, 'Product ID:') : 0 }} {{ __('app.items') }}</td><td>{{ Str::limit($adj->reason, 30) }}</td><td><a href="{{ route('stock.adjustments.show', $adj->id) }}" class="text-blue-600 hover:text-blue-800" title="{{ __('app.view') }}"><svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z"></path><path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path></svg></a></td></tr>@empty<tr><td colspan="8" class="text-center text-gray-500 py-8">{{ __('app.no_results') }}</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
