@extends('layouts.app')
@section('title', __('app.accounts'))
@php
$pageTitle = __('app.accounts');
$breadcrumbs = [['label' => __('app.dashboard'), 'url' => route('dashboard')], ['label' => __('app.accounting'), 'url' => '#'], ['label' => __('app.accounts'), 'url' => '']];
@endphp
@section('content')
<div class="card">
    <div class="card-header flex justify-between items-center"><h3 class="text-lg font-semibold text-gray-800">{{ __('app.accounts') }}</h3><a href="{{ route('accounting.accounts.create') }}" class="btn btn-primary btn-sm"><svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path></svg>{{ __('app.add') }} {{ __('app.accounts') }}</a></div>
    <div class="mb-4 grid grid-cols-1 md:grid-cols-3 gap-4"><div><select class="form-control"><option>{{ __('app.all') }} {{ __('app.type') }}</option><option value="asset">{{ __('app.asset') }}</option><option value="liability">{{ __('app.liability') }}</option><option value="equity">{{ __('app.equity') }}</option><option value="revenue">{{ __('app.revenue') }}</option><option value="expense">{{ __('app.expenses') }}</option></select></div><div><input type="text" placeholder="{{ __('app.search') }} {{ __('app.accounts') }}..." class="form-control"></div></div>
    <div class="overflow-x-auto"><table class="table"><thead><tr><th>{{ __('app.product_code') }}</th><th>{{ __('app.name') }}</th><th>{{ __('app.type') }}</th><th>{{ __('app.balance') }}</th><th>{{ __('app.status') }}</th><th>{{ __('app.actions') }}</th></tr></thead>
    <tbody>@forelse($accounts ?? [] as $account)<tr><td class="font-mono">{{ $account->code }}</td><td class="font-medium">{{ $account->name }}</td><td><span class="badge {{ $account->type == 'asset' ? 'badge-info' : ($account->type == 'liability' ? 'badge-warning' : ($account->type == 'revenue' ? 'badge-success' : 'badge-danger')) }}">{{ __('app.' . $account->type) }}</span></td><td class="font-semibold {{ $account->balance >= 0 ? 'text-green-600' : 'text-red-600' }}">{{ number_format($account->balance, 2) }} DH</td><td><span class="badge {{ $account->is_active ? 'badge-success' : 'badge-secondary' }}">{{ $account->is_active ? __('app.active') : __('app.inactive') }}</span></td><td><div class="flex space-x-2"><a href="{{ route('accounting.accounts.show', $account->id) }}" class="text-blue-600" title="{{ __('app.view') }}"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0zM2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg></a><a href="{{ route('accounting.accounts.edit', $account->id) }}" class="text-green-600" title="{{ __('app.edit') }}"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path></svg></a><form method="POST" action="{{ route('accounting.accounts.destroy', $account->id) }}" class="inline" onsubmit="return confirm('{{ __('app.confirm_delete') }}')">@csrf @method('DELETE')<button type="submit" class="text-red-600" title="{{ __('app.delete') }}"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg></button></form></div></td></tr>@empty<tr><td colspan="6" class="text-center text-gray-500 py-8">{{ __('app.no_results') }}</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
