@extends('layouts.app')
@section('title', 'Quotation Details')
@php
$pageTitle = 'Quotation Details';
$breadcrumbs = [['label' => 'Dashboard', 'url' => route('dashboard')], ['label' => 'Quotations', 'url' => route('quotations.index')], ['label' => $quotation->reference, 'url' => '']];
@endphp
@section('content')
<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
    <div class="lg:col-span-1"><div class="card"><h3 class="text-lg font-semibold text-gray-800 mb-4">Quotation Info</h3><dl class="space-y-3"><div><dt class="text-sm font-medium text-gray-500">Reference</dt><dd class="mt-1 text-sm font-semibold text-gray-900">{{ $quotation->reference }}</dd></div><div><dt class="text-sm font-medium text-gray-500">Customer</dt><dd class="mt-1 text-sm text-gray-900">{{ $quotation->customer->name }}</dd></div><div><dt class="text-sm font-medium text-gray-500">Quotation Date</dt><dd class="mt-1 text-sm text-gray-900">{{ optional($quotation->date)->format('M d, Y') }}</dd></div><div><dt class="text-sm font-medium text-gray-500">Valid Until</dt><dd class="mt-1 text-sm text-gray-900">{{ optional($quotation->valid_until)->format('M d, Y') }}</dd></div><div><dt class="text-sm font-medium text-gray-500">Status</dt><dd class="mt-1">@if($quotation->status == 'sent')<span class="badge badge-info">Sent</span>@elseif($quotation->status == 'accepted')<span class="badge badge-success">Accepted</span>@elseif($quotation->status == 'rejected')<span class="badge badge-danger">Rejected</span>@elseif($quotation->status == 'converted')<span class="badge badge-primary">Converted to Sale</span>@else<span class="badge badge-secondary">Draft</span>@endif</dd></div><div><dt class="text-sm font-medium text-gray-500">Created By</dt><dd class="mt-1 text-sm text-gray-900">{{ $quotation->user->full_name ?? 'N/A' }}</dd></div></dl><div class="mt-4 space-y-2"><a href="{{ route('quotations.edit', $quotation->id) }}" class="btn btn-primary w-full">Edit Quotation</a><a href="{{ route('quotations.print', $quotation->id) }}" target="_blank" class="btn btn-outline w-full"><svg class="w-4 h-4 mr-1 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>Print Quotation</a>@if($quotation->status != 'converted' && $quotation->status != 'rejected')<form method="POST" action="{{ route('quotations.convert', $quotation->id) }}">@csrf<button type="submit" class="btn btn-success w-full"><svg class="w-4 h-4 mr-1 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"></path></svg>Convert to Sale</button></form>@endif</div></div></div>
    <div class="lg:col-span-2 space-y-6"><div class="card"><h3 class="text-lg font-semibold text-gray-800 mb-4">Products</h3><div class="overflow-x-auto"><table class="table"><thead><tr><th>Product</th><th>SKU</th><th>Qty</th><th>Unit Price</th><th>Subtotal</th></tr></thead><tbody>@foreach($quotation->items ?? [] as $item)<tr><td class="font-medium">{{ $item->product->name }}</td><td>{{ $item->product->sku }}</td><td>{{ $item->quantity }}</td><td>{{ number_format($item->price, 2) }} DH</td><td class="font-semibold">{{ number_format($item->quantity * $item->price, 2) }} DH</td></tr>@endforeach</tbody></table></div></div>
    <div class="card"><h3 class="text-lg font-semibold text-gray-800 mb-4">Summary</h3><dl class="space-y-2"><div class="flex justify-between text-sm"><dt>Subtotal:</dt><dd class="font-semibold">{{ number_format($quotation->items->sum('subtotal'), 2) }} DH</dd></div><div class="flex justify-between text-sm"><dt>Tax:</dt><dd class="font-semibold">{{ number_format($quotation->tax_amount ?? 0, 2) }} DH</dd></div><div class="flex justify-between text-sm"><dt>Shipping:</dt><dd class="font-semibold">{{ number_format($quotation->shipping_cost ?? 0, 2) }} DH</dd></div><div class="flex justify-between text-sm"><dt>Discount:</dt><dd class="font-semibold text-red-600">-{{ number_format($quotation->discount_amount ?? 0, 2) }} DH</dd></div><div class="flex justify-between text-lg border-t border-gray-300 pt-2"><dt class="font-semibold">Total:</dt><dd class="font-bold text-blue-600">{{ number_format($quotation->total_amount, 2) }} DH</dd></div></dl></div>
    @if($quotation->terms)<div class="card"><h3 class="text-lg font-semibold text-gray-800 mb-4">Terms & Conditions</h3><p class="text-gray-700 whitespace-pre-line">{{ $quotation->terms }}</p></div>@endif</div>
</div>
@endsection
