@extends('layouts.app')
@section('title', __('app.tax_declaration'))
@php
$pageTitle = __('app.tax_declaration');
$breadcrumbs = [['label' => __('app.dashboard'), 'url' => route('dashboard')], ['label' => __('app.accounting'), 'url' => '#'], ['label' => __('app.tax'), 'url' => route('accounting.tax.index')], ['label' => __('app.tax_declaration'), 'url' => '']];
$declaration = $declaration ?? [];
@endphp
@section('content')
<div class="card mb-6">
    <div class="card-header flex justify-between items-center"><h3 class="text-lg font-semibold text-gray-800">{{ __('app.vat_tax_declaration') }}</h3><button onclick="window.print()" class="btn btn-outline btn-sm"><svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>{{ __('app.print_declaration') }}</button></div>
    <form method="GET" class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
        <div><label class="form-label">{{ __('app.declaration_period') }}</label><select name="period" class="form-control"><option value="monthly">{{ __('app.monthly') }}</option><option value="quarterly">{{ __('app.quarterly') }}</option><option value="annually">{{ __('app.annually') }}</option></select></div>
        <div><label class="form-label">{{ __('app.month_quarter_year') }}</label><select name="month" class="form-control"><option value="1">{{ __('app.january') }}</option><option value="2">{{ __('app.february') }}</option><option value="3">{{ __('app.march') }}</option><option value="4">{{ __('app.april') }}</option><option value="5">{{ __('app.may') }}</option><option value="6">{{ __('app.june') }}</option><option value="7">{{ __('app.july') }}</option><option value="8">{{ __('app.august') }}</option><option value="9">{{ __('app.september') }}</option><option value="10">{{ __('app.october') }}</option><option value="11">{{ __('app.november') }}</option><option value="12">{{ __('app.december') }}</option></select></div>
        <div class="flex items-end"><button type="submit" class="btn btn-primary w-full">{{ __('app.generate_declaration') }}</button></div>
    </form>
</div>

<div class="card">
    <h3 class="text-lg font-semibold text-gray-800 mb-4">{{ __('app.declaration_summary') }}</h3>
    <div class="space-y-6">
        <div class="border-b pb-4"><h4 class="font-semibold text-gray-700 mb-3">PART A - {{ __('app.output_tax') }} ({{ __('app.tax_on_sales') }})</h4><div class="overflow-x-auto"><table class="table"><thead><tr><th>{{ __('app.description') }}</th><th>{{ __('app.base_amount') }}</th><th>{{ __('app.tax_rate') }}</th><th>{{ __('app.tax_amount') }}</th></tr></thead><tbody><tr><td>{{ __('app.total_sales_standard') }}</td><td>{{ number_format($declaration['sales_base'] ?? 0, 2) }} DH</td><td>20%</td><td class="font-semibold">{{ number_format($declaration['sales_tax'] ?? 0, 2) }} DH</td></tr><tr><td>{{ __('app.total_sales_reduced') }}</td><td>{{ number_format($declaration['sales_reduced_base'] ?? 0, 2) }} DH</td><td>10%</td><td class="font-semibold">{{ number_format($declaration['sales_reduced_tax'] ?? 0, 2) }} DH</td></tr><tr><td>{{ __('app.tax_exempt_sales') }}</td><td>{{ number_format($declaration['sales_exempt'] ?? 0, 2) }} DH</td><td>0%</td><td>-</td></tr><tr class="bg-blue-50 font-semibold"><td>{{ __('app.total_output_tax') }}</td><td></td><td></td><td class="text-blue-700">{{ number_format(($declaration['sales_tax'] ?? 0) + ($declaration['sales_reduced_tax'] ?? 0), 2) }} DH</td></tr></tbody></table></div></div>
        <div class="border-b pb-4"><h4 class="font-semibold text-gray-700 mb-3">PART B - {{ __('app.input_tax') }} ({{ __('app.tax_on_purchases') }})</h4><div class="overflow-x-auto"><table class="table"><thead><tr><th>{{ __('app.description') }}</th><th>{{ __('app.base_amount') }}</th><th>{{ __('app.tax_rate') }}</th><th>{{ __('app.tax_amount') }}</th></tr></thead><tbody><tr><td>{{ __('app.total_purchases_standard') }}</td><td>{{ number_format($declaration['purchase_base'] ?? 0, 2) }} DH</td><td>20%</td><td class="font-semibold">{{ number_format($declaration['purchase_tax'] ?? 0, 2) }} DH</td></tr><tr><td>{{ __('app.total_purchases_reduced') }}</td><td>{{ number_format($declaration['purchase_reduced_base'] ?? 0, 2) }} DH</td><td>10%</td><td class="font-semibold">{{ number_format($declaration['purchase_reduced_tax'] ?? 0, 2) }} DH</td></tr><tr><td>{{ __('app.tax_exempt_purchases') }}</td><td>{{ number_format($declaration['purchase_exempt'] ?? 0, 2) }} DH</td><td>0%</td><td>-</td></tr><tr class="bg-blue-50 font-semibold"><td>{{ __('app.total_input_tax') }}</td><td></td><td></td><td class="text-blue-700">{{ number_format(($declaration['purchase_tax'] ?? 0) + ($declaration['purchase_reduced_tax'] ?? 0), 2) }} DH</td></tr></tbody></table></div></div>
        <div class="bg-gray-100 p-6 rounded-lg"><div class="space-y-3"><div class="flex justify-between text-lg"><span>{{ __('app.output_tax') }} (A):</span><span class="font-semibold">{{ number_format(($declaration['sales_tax'] ?? 0) + ($declaration['sales_reduced_tax'] ?? 0), 2) }} DH</span></div><div class="flex justify-between text-lg"><span>{{ __('app.input_tax') }} (B):</span><span class="font-semibold">{{ number_format(($declaration['purchase_tax'] ?? 0) + ($declaration['purchase_reduced_tax'] ?? 0), 2) }} DH</span></div><div class="flex justify-between text-2xl font-bold border-t-2 border-gray-300 pt-3 {{ ($declaration['net_tax'] ?? 0) >= 0 ? 'text-red-600' : 'text-green-600' }}"><span>{{ ($declaration['net_tax'] ?? 0) >= 0 ? __('app.tax_payable') : __('app.tax_refund') }}:</span><span>{{ number_format(abs($declaration['net_tax'] ?? 0), 2) }} DH</span></div></div></div>
    </div>
</div>
@endsection
