@extends('layouts.app')
@section('title', __('app.opportunities'))
@php
$pageTitle = __('app.opportunities');
$breadcrumbs = [['label' => __('app.dashboard'), 'url' => route('dashboard')], ['label' => __('app.crm'), 'url' => '#'], ['label' => __('app.opportunities'), 'url' => '']];
@endphp
@section('content')
<div class="card">
    <div class="card-header flex justify-between items-center"><h3 class="text-lg font-semibold text-gray-800">{{ __('app.sales_opportunities') }}</h3><a href="{{ route('crm.opportunities.create') }}" class="btn btn-primary btn-sm"><svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path></svg>{{ __('app.add_opportunity') }}</a></div>
    <div class="mb-4 grid grid-cols-1 md:grid-cols-4 gap-4"><div><input type="text" placeholder="{{ __('app.search') }} {{ __('app.opportunities') }}..." class="form-control"></div><div><select class="form-control"><option>{{ __('app.all_stages') }}</option><option value="prospecting">{{ __('app.prospecting') }}</option><option value="qualification">{{ __('app.qualification') }}</option><option value="proposal">{{ __('app.proposal') }}</option><option value="negotiation">{{ __('app.negotiation') }}</option><option value="closed_won">{{ __('app.closed_won') }}</option><option value="closed_lost">{{ __('app.closed_lost') }}</option></select></div><div><select class="form-control"><option>{{ __('app.all_probability') }}</option><option value="high">{{ __('app.high') }} (70-100%)</option><option value="medium">{{ __('app.medium') }} (30-70%)</option><option value="low">{{ __('app.low') }} (0-30%)</option></select></div><div><select class="form-control"><option>{{ __('app.all_assigned') }}</option>@foreach($users ?? [] as $u)<option value="{{ $u->id }}">{{ $u->name }}</option>@endforeach</select></div></div>
    <div class="overflow-x-auto"><table class="table"><thead><tr><th>{{ __('app.opportunity_name') }}</th><th>{{ __('app.account') }}</th><th>{{ __('app.amount') }}</th><th>{{ __('app.probability') }}</th><th>{{ __('app.stage') }}</th><th>{{ __('app.expected_close') }}</th><th>{{ __('app.assigned_to') }}</th><th>{{ __('app.actions') }}</th></tr></thead>
    <tbody>@forelse($opportunities ?? [] as $opp)<tr><td class="font-medium">{{ $opp->name }}</td><td>{{ $opp->account_name }}</td><td class="font-semibold text-green-600">{{ number_format($opp->amount, 2) }} DH</td><td><div class="flex items-center"><span class="text-sm font-semibold mr-2">{{ $opp->probability }}%</span><div class="w-20 bg-gray-200 rounded-full h-2"><div class="bg-blue-600 h-2 rounded-full" style="width: {{ $opp->probability }}%"></div></div></div></td><td><span class="badge {{ $opp->stage == 'closed_won' ? 'badge-success' : ($opp->stage == 'closed_lost' ? 'badge-danger' : 'badge-info') }}">{{ __('app.' . $opp->stage) }}</span></td><td>{{ $opp->expected_close_date->format('M d, Y') }}</td><td>{{ $opp->assignedTo->name ?? '-' }}</td><td><div class="flex space-x-2"><a href="{{ route('crm.opportunities.edit', $opp->id) }}" class="text-green-600" title="{{ __('app.edit') }}"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path></svg></a><form method="POST" action="{{ route('crm.opportunities.destroy', $opp->id) }}" class="inline" onsubmit="return confirm('{{ __('app.confirm_delete') }}')">@csrf @method('DELETE')<button type="submit" class="text-red-600" title="{{ __('app.delete') }}"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg></button></form></div></td></tr>@empty<tr><td colspan="8" class="text-center text-gray-500 py-8">{{ __('app.no_opportunities_found') }}</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
