@extends('layouts.app')
@section('title', __('app.activities'))
@php
$pageTitle = __('app.crm_activities');
$breadcrumbs = [['label' => __('app.dashboard'), 'url' => route('dashboard')], ['label' => __('app.crm'), 'url' => '#'], ['label' => __('app.activities'), 'url' => '']];
@endphp
@section('content')
<div class="card">
    <div class="card-header flex justify-between items-center"><h3 class="text-lg font-semibold text-gray-800">{{ __('app.activities_tasks') }}</h3><a href="{{ route('crm.activities.create') }}" class="btn btn-primary btn-sm"><svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path></svg>{{ __('app.log_activity') }}</a></div>
    <div class="mb-4 grid grid-cols-1 md:grid-cols-4 gap-4"><div><select class="form-control"><option>{{ __('app.all_types') }}</option><option value="call">{{ __('app.call') }}</option><option value="meeting">{{ __('app.meeting') }}</option><option value="email">{{ __('app.email') }}</option><option value="task">{{ __('app.task') }}</option><option value="note">{{ __('app.note') }}</option></select></div><div><select class="form-control"><option>{{ __('app.all_status') }}</option><option value="pending">{{ __('app.pending') }}</option><option value="completed">{{ __('app.completed') }}</option><option value="cancelled">{{ __('app.cancelled') }}</option></select></div><div><input type="date" class="form-control" placeholder="{{ __('app.from_date') }}"></div><div><input type="date" class="form-control" placeholder="{{ __('app.to_date') }}"></div></div>
    <div class="overflow-x-auto"><table class="table"><thead><tr><th>{{ __('app.type') }}</th><th>{{ __('app.subject') }}</th><th>{{ __('app.related_to') }}</th><th>{{ __('app.date') }}</th><th>{{ __('app.assigned_to') }}</th><th>{{ __('app.status') }}</th><th>{{ __('app.priority') }}</th><th>{{ __('app.actions') }}</th></tr></thead>
    <tbody>@forelse($activities ?? [] as $activity)<tr><td><span class="badge {{ $activity->type == 'call' ? 'badge-info' : ($activity->type == 'meeting' ? 'badge-success' : ($activity->type == 'email' ? 'badge-warning' : 'badge-secondary')) }}">{{ __('app.' . $activity->type) }}</span></td><td class="font-medium">{{ $activity->subject }}</td><td>{{ __('app.' . $activity->related_to_type) }}: {{ $activity->related_to_name ?? '-' }}</td><td>{{ $activity->activity_date->format('M d, Y h:i A') }}</td><td>{{ $activity->assignedTo->name ?? '-' }}</td><td><span class="badge {{ $activity->status == 'completed' ? 'badge-success' : ($activity->status == 'cancelled' ? 'badge-danger' : 'badge-warning') }}">{{ __('app.' . $activity->status) }}</span></td><td><span class="badge {{ $activity->priority == 'high' ? 'badge-danger' : ($activity->priority == 'medium' ? 'badge-warning' : 'badge-secondary') }}">{{ __('app.' . $activity->priority) }}</span></td><td><div class="flex space-x-2"><button onclick="viewActivity({{ $activity->id }})" class="text-blue-600"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path></svg></button><form method="POST" action="{{ route('crm.activities.destroy', $activity->id) }}" class="inline" onsubmit="return confirm('{{ __('app.confirm_delete') }}')">@csrf @method('DELETE')<button type="submit" class="text-red-600"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg></button></form></div></td></tr>@empty<tr><td colspan="8" class="text-center text-gray-500 py-8">{{ __('app.no_activities_found') }}</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
